### ISSUE TITLE
Lacking support for authToken from secure config.

### ISSUE THREAD

**Issue by JustinHarshbarger** [AmityCo/Amity-Social-Cloud-UIKit-Web-OpenSource#55]
### Initial checklist

- [X] I read the [support docs](https://community.amity.co/)
- [X] I read the [contributing guide](https://github.com/EkoCommunications/AmityUiKitWeb/blob/develop/CONTRIBUTING.md)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

Amity-Social-Cloud-UIKit-Web-OpenSource : Release v4.0.0-beta.2

### Steps to reproduce

Enable secure config and try to use the UI component. Node 18.14.2

### Expected behavior

Should accept and set the authToken on the client.

### Actual behavior

Client is set up without authToken and authentication of user fails.

### Runtime

Other (please specify in steps to reproduce)

### OS

macOS

### Build and bundle tools

Vite

**Comment by trustratch** [comment]
Hello @JustinHarshbarger! Thank you for bringing this to our attention. You can set the authToken using the code snippets provided below::
```
export default function Wrapper({ apiKey, apiEndpoint, userId, displayName }) => {
    const getAuthToken = async () => {
      const authToken = await getAuthTokenFromApi()
      return authToken;
    }
  
    return (
      <UiKitProvider
        ref={ref}
        apiKey={apiKey}
        apiEndpoint={apiEndpoint}
        userId={userId}
        displayName={displayName || userId}
        onConnected={handleConnected}
        onDisconnected={handleDisconnected}
        getAuthToken={getAuthToken}
      >
        <App
           connect={handleConnect}
           disconnect={handleDisconnect} />
      </UiKitProvider>
    )
  }
```
For more information please visit:
https://docs.amity.co/amity-uikit/uikit-v4-beta/setup-and-authentication/web-react

**Comment by trustratch** [comment]
If you need any additional support, may I suggest contacting support.asc@amity.co? Please feel free to reach out
